# Usar una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo del cliente al contenedor
COPY cliente.py ./  # Archivo del cliente

# Permitir configurar la dirección del servidor a través de una variable de entorno
ENV SERVER_HOST=servidor
ENV SERVER_PORT=8080

# Comando predeterminado para iniciar el cliente
CMD ["python", "cliente.py"]